# Generated by Django 4.1.7 on 2023-03-09 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("img", models.ImageField(upload_to="products")),
                ("price", models.IntegerField()),
                ("desc", models.TextField()),
                ("stock", models.IntegerField()),
                ("available", models.BooleanField()),
            ],
        ),
    ]
