# Generated by Django 4.1.7 on 2023-03-10 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_product_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="categories",
            options={
                "ordering": ("name",),
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ("name",),
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
            },
        ),
    ]
