# Generated by Django 4.1.7 on 2023-03-10 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_alter_categories_options_alter_product_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="available",
            new_name="availability",
        ),
    ]
