# Generated by Django 4.1.7 on 2023-03-12 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_rename_available_product_availability"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("qty", models.IntegerField()),
                (
                    "pd",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.product"
                    ),
                ),
            ],
        ),
    ]
