# Generated by Django 4.1.7 on 2023-03-12 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_cart"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="pd",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="main.product",
                unique=True,
            ),
        ),
    ]
