# Generated by Django 3.2.18 on 2023-03-12 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_cart_pd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='pd',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.product'),
        ),
    ]
