# Generated by Django 3.2.18 on 2023-03-12 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_cart_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
