# Generated by Django 4.1.7 on 2023-03-12 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0013_cart"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="price",
        ),
    ]
