# Generated by Django 4.1.7 on 2023-03-12 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0014_remove_cart_price"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cart",
            options={"verbose_name": "Cart", "verbose_name_plural": "Cart Items"},
        ),
    ]
