# Generated by Django 4.1.7 on 2023-03-12 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0015_alter_cart_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="price",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
