# Generated by Django 4.1.7 on 2023-03-12 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0016_cart_price"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Cart",
        ),
    ]
