# Generated by Django 4.1.7 on 2023-03-12 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0018_cart"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="price",
            field=models.IntegerField(),
        ),
    ]
