# Generated by Django 4.1.7 on 2023-03-12 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0019_alter_cart_price"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cart",
            options={
                "ordering": ("id",),
                "verbose_name": "Cart",
                "verbose_name_plural": "Cart Items",
            },
        ),
    ]
